openapi: 3.2.0
info:
  x-logo:
    url: https://coinpaprika.com/static/files/d6d3c6e3.svg#greywizard/rock-coin-web/assets/coin/img/cp-logo-beta.svg
    backgroundColor: '#FFFFFF'
  description: 'Coinpaprika API delivers free & frequently updated market data from the world of crypto: coin prices, volumes, market caps, ATHs, return rates and more.'
  version: 1.2.1
  title: Coinpaprika Coins API
servers:
- url: https://api.coinpaprika.com/v1
tags:
- name: Coins
paths:
  /coins:
    get:
      tags:
      - Coins
      summary: Get all coins listed on coinpaprika
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Coin'
        429:
          description: too many requests
      operationId: getCoins
      x-operation-id-source: derived
components:
  schemas:
    Coin:
      type: object
      properties:
        id:
          type: string
          example: btc-bitcoin
        name:
          type: string
          example: Bitcoin
        symbol:
          type: string
          example: BTC
        rank:
          type: integer
          example: 1
        is_new:
          type: boolean
          example: false
          description: If currency was added within last 5 days
        is_active:
          type: boolean
          example: true
