openapi: 3.2.0
info:
  x-logo:
    url: https://coinpaprika.com/static/files/d6d3c6e3.svg#greywizard/rock-coin-web/assets/coin/img/cp-logo-beta.svg
    backgroundColor: '#FFFFFF'
  description: 'Coinpaprika API delivers free & frequently updated market data from the world of crypto: coin prices, volumes, market caps, ATHs, return rates and more.'
  version: 1.2.1
  title: Coinpaprika Global API
servers:
- url: https://api.coinpaprika.com/v1
tags:
- name: Global
paths:
  /global:
    get:
      tags:
      - Global
      summary: Get global information
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Global'
        429:
          description: too many requests
      operationId: getGlobal
      x-operation-id-source: derived
components:
  schemas:
    Global:
      type: object
      properties:
        market_cap_usd:
          type: number
          example: 430252937008
        volume_24h_usd:
          type: number
          example: 430252937008
        bitcoin_dominance_percentage:
          type: number
          example: 36.67
        cryptocurrencies_number:
          type: integer
          example: 1587
        last_updated:
          type: integer
          example: 1525089441
